# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2021-02-20 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=100, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u59d3\u540d')),
                ('sex', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=5, verbose_name='\u6027\u522b')),
                ('course', models.ManyToManyField(to='curdtest.Course')),
            ],
        ),
    ]
