# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2021-02-22 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=8, verbose_name='\u6027\u522b'),
        ),
    ]
