# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2021-02-20 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='\u516c\u53f8\u540d\u79f0')),
                ('images', models.CharField(default='', max_length=300, verbose_name='\u4e0a\u4f20\u56fe\u7247')),
                ('video', models.CharField(default='', max_length=200, verbose_name='\u4e0a\u4f20\u89c6\u9891')),
            ],
            options={
                'verbose_name': '\u771f\u5b9e\u4fe1\u606f',
                'verbose_name_plural': '\u771f\u5b9e\u4fe1\u606f',
            },
        ),
    ]
